import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Sidebar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="grid grid-cols-[288px,1fr]">
          <Sidebar />
          <main className="pr-7">{children}</main>
        </div>
      </body>
    </html>
  );
}
